<?xml version="1.0"?>
<robot name="jackal" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="0.262" />
  <xacro:property name="track" value="0.37559" />
  <xacro:property name="wheel_vertical_offset" value="0.0345" />
  <xacro:property name="footprint_vertical_offset" value="-0.0655" />

  <xacro:property name="wheel_radius" value="0.098" />
  <xacro:property name="wheel_width" value="0.040" />

  <xacro:property name="chassis_length" value="0.420" />
  <xacro:property name="chassis_width" value="0.310" />
  <xacro:property name="chassis_height" value="0.184" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.115" />
  <xacro:property name="velodyne_height" value="0.5" />
  <xacro:property name="long_beam" value="0.35" />
  <xacro:property name="short_beam" value="0.135" />
  <xacro:property name="plate_thickness" value="0.005" />

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>
  <material name="alu"><color rgba="0.56 0.56 0.56 1.0" /></material>

<xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://jackal_description/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

    <!-- In reality, Jackal has only two motors, one per side. However, it's more
         straightforward for Gazebo to simulate as if there's an actuator per wheel. -->
    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <mechanicalReduction>10</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:wheel prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>


  <link name="base_link"></link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis_link" />
  </joint>

  <link name="chassis_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="package://jackal_description/meshes/jackal-base.stl"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Center of mass -->
      <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
      <mass value="16.523"/>
      <!-- Moments of inertia: ( chassis without wheels ) -->
      <inertia
        ixx="0.3136" ixy="-0.0008" ixz="0.0164"
        iyy="0.3922" iyz="-0.0009"
        izz="0.4485"/>
      </inertial>
  </link>

  <link name="fenders_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="package://jackal_description/meshes/jackal-fenders.stl"/>
      </geometry>
      <material name="yellow" />
    </visual>
  </link>
  <joint name="fenders_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="fenders_link" />
  </joint>

  <!-- TODO: Make this internal_imu_link or something, and use a mixed-in xacro
       to supply the joint between it and imu_link. This is important so that imu_link
       always points to the "active" IMU. When an upgrade IMU is connected, the
       internal_imu_link should remain, but imu_link should point to the upgrade one. -->
  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="imu_link" />
  </joint>

  <!-- TODO: Same note as applies to imu_link -->
  <link name="navsat_link">
    <visual>
      <geometry>
        <cylinder radius="0.026" length="0.016" />
      </geometry>
      <origin xyz="0 0 0.008" />
      <material name="black" />
    </visual>
  </link>
  <joint name="navsat_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="navsat_link" />
    <origin xyz="-0.180 0.126 0.1815" />
  </joint>

  <link name="mid_mount"></link>
  <joint name="mid_mount_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="mid_mount" />
    <origin xyz="0 0 ${chassis_height}" />
  </joint>

  <link name="rear_mount"></link>
  <joint name="rear_mount_joint" type="fixed">
    <parent link="mid_mount" />
    <child link="rear_mount" />
    <origin xyz="${-mount_spacing} 0 0" />
  </joint>

  <joint name="front_mount_joint" type="fixed">
    <parent link="mid_mount" />
    <child link="hokuyo_base_link" />
    <origin xyz="${mount_spacing} 0 0.015" />
  </joint>

  <link name="front_mount"></link>
  <joint name="front_mount_joint_2" type="fixed">
    <parent link="mid_mount" />
    <child link="front_mount" />
    <origin xyz="${mount_spacing} 0 0" />
  </joint>
  <joint name="baseplate_mount_joint" type="fixed">
    <parent link="mid_mount"/>
    <child link="baseplate_link"/>
    <origin xyz="0 0 0.01"/>
  </joint>

  <link name="baseplate_link">
    <visual>
      <origin xyz="0.05 0 ${plate_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.3 ${plate_thickness}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="-0.15 0 ${plate_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.16 ${plate_thickness}"/>
      </geometry>
      <material name="alu"/>
    </visual>
    <visual>
      <origin xyz="-0.077 -0.105 ${long_beam/2 + plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${long_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="0.038 -0.105 ${long_beam/2 + plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${long_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="-0.077 0.105 ${long_beam/2 + plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${long_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="0.038 0.105 ${long_beam/2 + plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${long_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="-0.0195 0 ${long_beam + 3*plate_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.145 0.24 ${plate_thickness}" />
      </geometry>
      <material name="alu" />
    </visual>
<!-- SHORT BEAMS -->    
    <visual>
      <origin xyz="-0.077 -0.07 ${long_beam + short_beam/2 + 2*plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${short_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="0.038 -0.07 ${long_beam + short_beam/2 + 2*plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${short_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="-0.077 0.07 ${long_beam + short_beam/2 + 2*plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${short_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="0.038 0.07 ${long_beam + short_beam/2 + 2*plate_thickness}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 ${short_beam}" />
      </geometry>
      <material name="alu" />
    </visual>
    <visual>
      <origin xyz="-0.0195 0 ${long_beam + short_beam + 5*plate_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.145 0.17 ${plate_thickness}" />
      </geometry>
      <material name="alu" />
    </visual>
  </link>

  <link name="hokuyo_base_link">
    <visual>
      <origin xyz="0 0 0.0205" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.041"/>
      </geometry>      
      <material name="black"/>
    </visual>
    <visual>
      <origin xyz="-0.021 0 0.049" rpy="0 0 0"/>
      <geometry>
        <box size="0.008 0.012 0.022"/>
      </geometry>      
      <material name="black"/>
    </visual>
    <visual>
      <origin xyz="0 0 0.06" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.019" length="0.02"/>
      </geometry>      
      <material name="black"/>
    </visual>
    <visual>
      <origin xyz="0 0 0.0455" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.021" length="0.009"/>
      </geometry>      
      <material name="black"/>
    </visual>
  </link>

  <link name="hokuyo_base_scan"></link>
  <joint name="hokuyo_base_scan_joint" type="fixed" >
       <origin xyz="0 0 0.0563" rpy="0 0 0" />
       <parent link="hokuyo_base_link" />
       <child link="hokuyo_base_scan"/>
  </joint>
  
  <joint name="$VLP16_base_mount_joint" type="fixed">
      <parent link="mid_mount"/>
      <child link="VLP16_base_link"/>
      <origin xyz="0 0 ${velodyne_height + 0.01}" /> 
  </joint>

  <link name="VLP16_base_link">
      <inertial>
        <mass value="0.1"/>
       <origin xyz="0 0 0"/>
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://velodyne_description/meshes/VLP16_base_1.dae" />
        </geometry>
      </visual>
      <visual>
        <geometry>
          <mesh filename="package://velodyne_description/meshes/VLP16_base_2.dae" />
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.03585"/>
        <geometry>
          <cylinder radius="0.0516" length="0.0717"/>
        </geometry>
      </collision>
  </link>

  <joint name="VLP16_base_scan_joint" type="fixed" >
       <origin xyz="0 0 0.0377" rpy="0 0 0" />
       <parent link="VLP16_base_link" />
       <child link="VLP16"/>
  </joint>

  <link name="VLP16">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
      </inertial>
      <visual>
        <origin xyz="0 0 -0.0377" />
        <geometry>
          <mesh filename="package://velodyne_description/meshes/VLP16_scan.dae" />
        </geometry>
      </visual>
  </link>
  
  <!--<link name="front_camera_link">
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>
  <joint name="front_camera_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="front_camera_link"/>
    <origin xyz="0 -0.4 1.4" rpy="0 0.05 -1.5707"/>
  </joint> -->

  <!-- Bring in simulation data for Gazebo. -->
  <xacro:include filename="jackal.gazebo" />

  <!-- Optional standard accessories, including their simulation data. The rendering
       of these into the final description is controlled by optenv variables, which
       default each one to off.-->
  <xacro:include filename="accessories.urdf.xacro" />

  <!-- Optional custom includes. -->
  <xacro:include filename="$(optenv JACKAL_URDF_EXTRAS empty.urdf)" />
</robot>
